// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Android Firebase app used for live content, Google authentication, and
  /// user profiles. The daily scraper service account writes to this project.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgTUysddSs22iwBc-zjGxeaDwpODzBt8U',
    appId: '1:906645524405:android:838f1c73e83ff7a0dc53fc',
    messagingSenderId: '906645524405',
    projectId: 'upsc-app-e2475-e5c95',
    storageBucket: 'upsc-app-e2475-e5c95.firebasestorage.app',
  );

  /// Kept as a semantic alias for authentication call sites.
  static const FirebaseOptions androidAuth = android;

  /// OAuth web client paired with the Android sign-in project.
  static const String androidAuthWebClientId =
      '906645524405-ifrp69c4lq4m2e5umjlpk428d099nn0h.apps.googleusercontent.com';

  /// Web app registered in the same live project as Android and the scraper.
  /// Keeping every platform on one project prevents routes from showing a
  /// different/empty collection in the browser. Generated from the Firebase
  /// Management API by backend/content-scraper/ensure-web-app.js.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACReA-zvqA5sr9WRCenhtlEpcrom7_WtA',
    appId: '1:906645524405:web:a97f474e5ff2c9b0dc53fc',
    messagingSenderId: '906645524405',
    projectId: 'upsc-app-e2475-e5c95',
    authDomain: 'upsc-app-e2475-e5c95.firebaseapp.com',
    databaseURL:
        'https://upsc-app-e2475-e5c95-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'upsc-app-e2475-e5c95.firebasestorage.app',
  );
}
